# Generated by Django 5.0.2 on 2024-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0002_exercise_protein_sleep_user_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='completed_at',
            new_name='completedAt',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='completed_at',
            new_name='completedAt',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='end_at',
            new_name='endAt',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='start_at',
            new_name='startAt',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bmi',
            new_name='BMI',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_lb',
            field=models.IntegerField(null=True),
        ),
    ]
