# Generated by Django 5.0.2 on 2024-02-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0003_rename_completed_at_exercise_completedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='BMI',
            new_name='bmi',
        ),
    ]
