# Generated by Django 5.0.2 on 2024-02-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0004_rename_bmi_user_bmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='completedAt',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='completedAt',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='endAt',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='startAt',
            new_name='start_at',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='userID',
            new_name='user_id',
        ),
    ]
