# Generated by Django 5.0.2 on 2024-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0005_rename_completedat_exercise_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user_id',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protein',
            name='user_id',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='user_id',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
